### ISSUE TITLE
Better error tracking and logging

### ISSUE THREAD

**Issue by Kiedtl** [lptstr/mouse#12]
Mouse currently does not report exceptions that occur to a central bug tracking database, it instead merely shows a generated error string to the user, which I strongly suspect never will be possible be reported.
I suggest that we utilize Sentry.io to store our error reports and then export them to GitHub Issues. Yes, Sentry DOES NOT support PowerShell, but it does support  .NET Standard/Core/Framework/Whatever, so we can either:
* write our own class to report errors
* or utilize [vtsingaras/RavenPowerShell](Mouse currently does not report exceptions that occur to a central bug tracking database, it instead merely shows a generated error string to the user, which I strongly suspect never will be possible be reported.
I suggest that we utilize Sentry.io to store our error reports and then export them to GitHub Issues. Yes, Sentry DOES NOT support PowerShell, but it does support  .NET Standard/Core/Framework/Whatever, so we can either:
* write our own class to report errors
* or utilize [vtsingaras/RavenPowerShell), which I strongly recommend.
I tried out the RavenPowerShell class, but it seemed pretty buggy. After hooking it up to this function:
```powershell
. "C:\Users\blah\mouse\lib\ravenclient.ps1"
. "C:\Users\blah\mouse\lib\errors.ps1"
[string]$dsn = "<blah blah blah blah blah blah blah blah>"

$ravenClient = New-RavenClient -SentryDsn $dsn

try {
    throw "big bad error"

} catch {
    $ravenClient.CaptureException($_)
}
```
I received several errors.
Anyway.
I think we can just debug this class and add it to our project.

Another thing we need to think about is a better logging scheme.
For v1.2.0, we should add a `--show-logs` flag to all our commands that will output detailed logging information, including the output of Git and Git-Crypt, which is currently being silenced. It will make life a lot easier for the people who test and debug this application. Even when the logging flags are not set, Mouse should **still** log to a file (which I think ought to be in `share/logs/whateverlogsname.log`, but it could be anywhere else).

I think that the logging feature should be implemented in the same way that every other class on Mouse is implemented, by creating a file `lib/logging.ps1` and implementing a function of the type `function Write-Log([string]$outmachine, [string]$statuscode, [string]$text, [string]$outfile );` where the `$outmachine` is the program producing the output (like Git or Mouse or Git_Crypt), where the statuscode is the statuscode, and the text is the log itself.
The log should follow the form of <DATE><APP><CODE>:<TEXT>:
```
2019-01-07T11:31:58.5634006-05:00 MOUSE UE404: The file or directory requested was not found.
```

**Comment by Kiedtl** [comment]
I just realized I am talking to myself.

**Comment by Kiedtl** [comment]
As of January 7th, 2019, the error reporting features have been fully implemented, now only the logging feature remains.

**Comment by Kiedtl** [comment]
- [x] build Sentry client
- [x] Customize client
- [x] Integrate client with Mouse
- [x] Implement logging function in `lib/core.ps1`
- [x] Integrate logging with Mouse

**Comment by Kiedtl** [comment]
Currently, the loggin feature for the add command is implemented, I think I can defer the rest for another time.
